/* Generated by tools/generate-word-audio-map.js. Do not edit manually. */
window.ICIBA_WORD_AUDIO = Object.freeze({
  "English": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/78/46/78463a384a5aa4fad5fa73e2f506ecfc.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/78/46/78463a384a5aa4fad5fa73e2f506ecfc.mp3"
  },
  "about": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/46/b3/46b3931b9959c927df4fc65fdee94b07.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/46/b3/46b3931b9959c927df4fc65fdee94b07.mp3"
  },
  "age": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/7d/63/7d637d275668ed6d41a9b97e6ad3a556.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/7d/63/7d637d275668ed6d41a9b97e6ad3a556.mp3"
  },
  "air": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/3c/45/3c4588116394d2164657875b7430907e.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/3c/45/3c4588116394d2164657875b7430907e.mp3"
  },
  "apple": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/1f/38/1f3870be274f6c49b3e31a0c6728957f.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/1f/38/1f3870be274f6c49b3e31a0c6728957f.mp3"
  },
  "baby": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/68/48/6848d756da66e55b42f79c0728e351ad.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/68/48/6848d756da66e55b42f79c0728e351ad.mp3"
  },
  "bad": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/ba/e6/bae60998ffe4923b131e3d6e4c19993e.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/ba/e6/bae60998ffe4923b131e3d6e4c19993e.mp3"
  },
  "bag": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/4a/82/4a82715423d654d61838e81060a4cdf1.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/4a/82/4a82715423d654d61838e81060a4cdf1.mp3"
  },
  "ball": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/7a/10/7a10ea1b9b2872da9f375002c44ddfce.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/7a/10/7a10ea1b9b2872da9f375002c44ddfce.mp3"
  },
  "banana": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/72/b3/72b302bf297a228a75730123efef7c41.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/72/b3/72b302bf297a228a75730123efef7c41.mp3"
  },
  "bath": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/d0/1b/d01befa8b1782c295a1d49d910522baf.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/d0/1b/d01befa8b1782c295a1d49d910522baf.mp3"
  },
  "bear": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/89/3b/893b56e3cfe153fb770a120b83bac20c.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/89/3b/893b56e3cfe153fb770a120b83bac20c.mp3"
  },
  "bed": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/00/1c/001cbc059a402b3be7c99be558eaaf73.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/00/1c/001cbc059a402b3be7c99be558eaaf73.mp3"
  },
  "beds": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/de/d1/ded15c530f0d1d5fb402905c8774102c.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/de/d1/ded15c530f0d1d5fb402905c8774102c.mp3"
  },
  "beer": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/3e/18/3e1867f5aee83045775fbe355e6a3ce1.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/3e/18/3e1867f5aee83045775fbe355e6a3ce1.mp3"
  },
  "behind": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/9d/a3/9da3be8f92c0bbfd7a7d6d6ec0b3fad3.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/9d/a3/9da3be8f92c0bbfd7a7d6d6ec0b3fad3.mp3"
  },
  "big": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/d8/61/d861877da56b8b4ceb35c8cbfdf65bb4.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/d8/61/d861877da56b8b4ceb35c8cbfdf65bb4.mp3"
  },
  "bird": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/ab/ae/abaecf8ca3f98dc13eeecbac263cd3ed.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/ab/ae/abaecf8ca3f98dc13eeecbac263cd3ed.mp3"
  },
  "blue": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/48/d6/48d6215903dff56238e52e8891380c8f.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/48/d6/48d6215903dff56238e52e8891380c8f.mp3"
  },
  "book": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/82/1f/821f03288846297c2cf43c34766a38f7.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/82/1f/821f03288846297c2cf43c34766a38f7.mp3"
  },
  "box": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/34/be/34be958a921e43d813a2075297d8e862.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/34/be/34be958a921e43d813a2075297d8e862.mp3"
  },
  "boy": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/1a/69/1a699ad5e06aa8a6db3bcf9cfb2f00f2.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/1a/69/1a699ad5e06aa8a6db3bcf9cfb2f00f2.mp3"
  },
  "bread": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/db/a7/dba7b12a19fe9d49fbb53d65c49bbce6.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/db/a7/dba7b12a19fe9d49fbb53d65c49bbce6.mp3"
  },
  "breathe": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/f3/28/f328976dae9176803fb936097e4d84de.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/f3/28/f328976dae9176803fb936097e4d84de.mp3"
  },
  "bridge": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/98/ac/98ac6b4b086b5a2f47677b15e786d9ba.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/98/ac/98ac6b4b086b5a2f47677b15e786d9ba.mp3"
  },
  "brother": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/e5/11/e511e2a4a4b88e45e210c770b932afb7.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/e5/11/e511e2a4a4b88e45e210c770b932afb7.mp3"
  },
  "bus": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/d2/0f/d20f83ee6933aa1ea047fe5cbd9c1fd5.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/d2/0f/d20f83ee6933aa1ea047fe5cbd9c1fd5.mp3"
  },
  "car": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/e6/d9/e6d96502596d7e7887b76646c5f615d9.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/e6/d9/e6d96502596d7e7887b76646c5f615d9.mp3"
  },
  "cards": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/49/2e/492e6640145b729207a5816b2fdb47f3.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/49/2e/492e6640145b729207a5816b2fdb47f3.mp3"
  },
  "care": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/88/d9/88d923ba797e9cafdfa4176f02bc2537.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/88/d9/88d923ba797e9cafdfa4176f02bc2537.mp3"
  },
  "carry": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/f9/c0/f9c05403344bba5b3993d54797b56820.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/f9/c0/f9c05403344bba5b3993d54797b56820.mp3"
  },
  "cat": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/d0/77/d077f244def8a70e5ea758bd8352fcd8.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/d0/77/d077f244def8a70e5ea758bd8352fcd8.mp3"
  },
  "cats": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/08/32/0832c1202da8d382318e329a7c133ea0.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/08/32/0832c1202da8d382318e329a7c133ea0.mp3"
  },
  "chair": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/a0/92/a09272b53419ab95507cdf127329336d.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/a0/92/a09272b53419ab95507cdf127329336d.mp3"
  },
  "cheese": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/fe/a0/fea0f1f6fede90bd0a925b4194deac11.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/fe/a0/fea0f1f6fede90bd0a925b4194deac11.mp3"
  },
  "children": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/26/81/268184c12df027f536154d099d497b31.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/26/81/268184c12df027f536154d099d497b31.mp3"
  },
  "choice": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/01/62/0162cefc4952304026cb1f5dab2419d2.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/01/62/0162cefc4952304026cb1f5dab2419d2.mp3"
  },
  "clock": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/05/53/05531b19bb846b18c09f979eeb429ad3.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/05/53/05531b19bb846b18c09f979eeb429ad3.mp3"
  },
  "coffee": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/24/eb/24eb05d18318ac2db8b2b959315d10f2.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/24/eb/24eb05d18318ac2db8b2b959315d10f2.mp3"
  },
  "come": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/12/de/12de3a4dab98ef8a7d67aace8150b540.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/12/de/12de3a4dab98ef8a7d67aace8150b540.mp3"
  },
  "could": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/f0/44/f0441366488bd123be0e5fb7d6c03c2b.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/f0/44/f0441366488bd123be0e5fb7d6c03c2b.mp3"
  },
  "country": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/e9/09/e909c2d7067ea37437cf97fe11d91bd0.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/e9/09/e909c2d7067ea37437cf97fe11d91bd0.mp3"
  },
  "cup": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/f3/f5/f3f58ee455ae41da2ad5de06bf55e8de.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/f3/f5/f3f58ee455ae41da2ad5de06bf55e8de.mp3"
  },
  "cure": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/1a/e4/1ae4b2115e7d11cc443fcf46f007fc10.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/1a/e4/1ae4b2115e7d11cc443fcf46f007fc10.mp3"
  },
  "day": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/62/8b/628b7db04235f228d40adc671413a8c8.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/62/8b/628b7db04235f228d40adc671413a8c8.mp3"
  },
  "decision": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/b9/b9/b9b9e36c1a5d1be22158df398f2e29b8.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/b9/b9/b9b9e36c1a5d1be22158df398f2e29b8.mp3"
  },
  "desk": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/b5/06/b506e098cf253ce028b8ba0a5fc7d473.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/b5/06/b506e098cf253ce028b8ba0a5fc7d473.mp3"
  },
  "dinner": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/ad/5a/ad5acdfacefd7f31104b3d7c9cffad6f.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/ad/5a/ad5acdfacefd7f31104b3d7c9cffad6f.mp3"
  },
  "dog": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/06/d8/06d80eb0c50b49a509b49f2424e8c805.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/06/d8/06d80eb0c50b49a509b49f2424e8c805.mp3"
  },
  "door": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/2f/ea/2feaaf89c21770ea5c21196bc33848dd.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/2f/ea/2feaaf89c21770ea5c21196bc33848dd.mp3"
  },
  "draw": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/81/74/817491bc777731f0f0c6e485f28e4d86.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/81/74/817491bc777731f0f0c6e485f28e4d86.mp3"
  },
  "dream": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/88/12/8812662dcf3e5db0247c0f85909363fc.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/88/12/8812662dcf3e5db0247c0f85909363fc.mp3"
  },
  "dress": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/cc/aa/ccaaac957ec37bde4c9993a26a064730.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/cc/aa/ccaaac957ec37bde4c9993a26a064730.mp3"
  },
  "drive": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/4a/a1/4aa1e7414849577e6d4c076c08782d3a.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/4a/a1/4aa1e7414849577e6d4c076c08782d3a.mp3"
  },
  "ear": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/d8/ff/d8ff99616fc9df8a54a32eec86ba8109.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/d8/ff/d8ff99616fc9df8a54a32eec86ba8109.mp3"
  },
  "easy": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/48/bb/48bb6e862e54f2a795ffc4e541caed4d.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/48/bb/48bb6e862e54f2a795ffc4e541caed4d.mp3"
  },
  "enjoy": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/76/e3/76e369257240ded4b1c059cf20e8d9a4.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/76/e3/76e369257240ded4b1c059cf20e8d9a4.mp3"
  },
  "face": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/d5/ca/d5ca322453f2986b752e58b11af83d96.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/d5/ca/d5ca322453f2986b752e58b11af83d96.mp3"
  },
  "family": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/0d/3f/0d3fda0bdbb9d619e09cdf3eecba7999.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/0d/3f/0d3fda0bdbb9d619e09cdf3eecba7999.mp3"
  },
  "far": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/17/d9/17d965747c701d6ffb406cad0f4265dc.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/17/d9/17d965747c701d6ffb406cad0f4265dc.mp3"
  },
  "fine": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/ff/f2/fff25994ee3941b225ba898fd17d186f.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/ff/f2/fff25994ee3941b225ba898fd17d186f.mp3"
  },
  "fish": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/83/e4/83e4a96aed96436c621b9809e258b309.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/83/e4/83e4a96aed96436c621b9809e258b309.mp3"
  },
  "five": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/30/05/30056e1cab7a61d256fc8edd970d14f5.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/30/05/30056e1cab7a61d256fc8edd970d14f5.mp3"
  },
  "food": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/62/50/62506be34d574da4a0d158a67253ea99.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/62/50/62506be34d574da4a0d158a67253ea99.mp3"
  },
  "foot": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/d8/73/d8735f7489c94f42f508d7eb1c249584.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/d8/73/d8735f7489c94f42f508d7eb1c249584.mp3"
  },
  "friend": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/3a/f0/3af00c6cad11f7ab5db4467b66ce503e.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/3a/f0/3af00c6cad11f7ab5db4467b66ce503e.mp3"
  },
  "friends": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/28/f2/28f20a02bf8a021fab4fcec48afb584e.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/28/f2/28f20a02bf8a021fab4fcec48afb584e.mp3"
  },
  "full": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/e9/dc/e9dc924f238fa6cc29465942875fe8f0.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/e9/dc/e9dc924f238fa6cc29465942875fe8f0.mp3"
  },
  "girl": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/28/ca/28ca53d2b7bb4aa13549b4022c79dca1.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/28/ca/28ca53d2b7bb4aa13549b4022c79dca1.mp3"
  },
  "go": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/34/d1/34d1f91fb2e514b8576fab1a75a89a6b.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/34/d1/34d1f91fb2e514b8576fab1a75a89a6b.mp3"
  },
  "good": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/75/5f/755f85c2723bb39381c7379a604160d8.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/75/5f/755f85c2723bb39381c7379a604160d8.mp3"
  },
  "green": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/9f/27/9f27410725ab8cc8854a2769c7a516b8.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/9f/27/9f27410725ab8cc8854a2769c7a516b8.mp3"
  },
  "guests": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/93/66/9366a2751ef2a1c1d4d98cc377d61e8c.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/93/66/9366a2751ef2a1c1d4d98cc377d61e8c.mp3"
  },
  "hair": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/2c/5c/2c5ca38849d1b0b961844c065214ff1a.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/2c/5c/2c5ca38849d1b0b961844c065214ff1a.mp3"
  },
  "hand": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/57/3c/573ce5969e9884d49d4fab77b09a306a.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/57/3c/573ce5969e9884d49d4fab77b09a306a.mp3"
  },
  "hands": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/6c/8d/6c8d61508321ac444175370124200350.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/6c/8d/6c8d61508321ac444175370124200350.mp3"
  },
  "happy": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/56/ab/56ab24c15b72a457069c5ea42fcfc640.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/56/ab/56ab24c15b72a457069c5ea42fcfc640.mp3"
  },
  "hat": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/46/b5/46b5e59b2fd342bf8fee10c561958725.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/46/b5/46b5e59b2fd342bf8fee10c561958725.mp3"
  },
  "heart": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/31/89/3189934774aa880fa7fbf8da8f9e446d.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/31/89/3189934774aa880fa7fbf8da8f9e446d.mp3"
  },
  "hello": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/5d/41/5d41402abc4b2a76b9719d911017c592.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/5d/41/5d41402abc4b2a76b9719d911017c592.mp3"
  },
  "here": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/6c/92/6c92285fa6d3e827b198d120ea3ac674.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/6c/92/6c92285fa6d3e827b198d120ea3ac674.mp3"
  },
  "high": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/8d/96/8d966b2253a917086c8604959e152243.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/8d/96/8d966b2253a917086c8604959e152243.mp3"
  },
  "home": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/10/6a/106a6c241b8797f52e1e77317b96a201.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/10/6a/106a6c241b8797f52e1e77317b96a201.mp3"
  },
  "horse": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/f1/bd/f1bdf5ed1d7ad7ede4e3809bd35644b0.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/f1/bd/f1bdf5ed1d7ad7ede4e3809bd35644b0.mp3"
  },
  "hot": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/27/36/27369b3bf4483e8dcfd85ba9a39a947f.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/27/36/27369b3bf4483e8dcfd85ba9a39a947f.mp3"
  },
  "house": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/2c/a6/2ca63cddd54f9490efad22421891a9d1.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/2c/a6/2ca63cddd54f9490efad22421891a9d1.mp3"
  },
  "how": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/db/88/db88a0257c220dbfdd2e40f6152d6a8d.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/db/88/db88a0257c220dbfdd2e40f6152d6a8d.mp3"
  },
  "idea": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/1c/ba/1cba77c39b4d0a81024a7aada3655a28.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/1c/ba/1cba77c39b4d0a81024a7aada3655a28.mp3"
  },
  "is": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/a2/a5/a2a551a6458a8de22446cc76d639a9e9.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/a2/a5/a2a551a6458a8de22446cc76d639a9e9.mp3"
  },
  "job": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/9d/dd/9dddd5ce1b1375bc497feeb871842d4b.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/9d/dd/9dddd5ce1b1375bc497feeb871842d4b.mp3"
  },
  "jump": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/ba/53/ba535ef5a9f7b8bc875812bb081286bb.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/ba/53/ba535ef5a9f7b8bc875812bb081286bb.mp3"
  },
  "key": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/3c/6e/3c6e0b8a9c15224a8228b9a98ca1531d.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/3c/6e/3c6e0b8a9c15224a8228b9a98ca1531d.mp3"
  },
  "king": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/b2/08/b2086154f101464aab3328ba7e060deb.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/b2/08/b2086154f101464aab3328ba7e060deb.mp3"
  },
  "late": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/f2/c6/f2c67381db28fa11c59fe7a6df0f2587.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/f2/c6/f2c67381db28fa11c59fe7a6df0f2587.mp3"
  },
  "leaf": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/ba/b4/bab4ff04cc14af66e4d42c85f888cfe6.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/ba/b4/bab4ff04cc14af66e4d42c85f888cfe6.mp3"
  },
  "learn": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/33/9d/339d8d14024f2ae5c8dc2e07362eba1d.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/33/9d/339d8d14024f2ae5c8dc2e07362eba1d.mp3"
  },
  "light": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/2a/c4/2ac43aa43bf473f9a9c09b4b608619d3.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/2a/c4/2ac43aa43bf473f9a9c09b4b608619d3.mp3"
  },
  "like": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/be/1a/be1ab1632e4285edc3733b142935c60b.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/be/1a/be1ab1632e4285edc3733b142935c60b.mp3"
  },
  "live": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/d0/db/d0dbe915091d400bd8ee7f27f0791303.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/d0/db/d0dbe915091d400bd8ee7f27f0791303.mp3"
  },
  "long": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/0f/52/0f5264038205edfb1ac05fbb0e8c5e94.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/0f/52/0f5264038205edfb1ac05fbb0e8c5e94.mp3"
  },
  "lot": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/20/9f/209f2308333b9973de9b4ea31d526b89.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/20/9f/209f2308333b9973de9b4ea31d526b89.mp3"
  },
  "lots": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/2e/c0/2ec001fcda7f781cac039579ca1ec170.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/2e/c0/2ec001fcda7f781cac039579ca1ec170.mp3"
  },
  "love": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/b5/c0/b5c0b187fe309af0f4d35982fd961d7e.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/b5/c0/b5c0b187fe309af0f4d35982fd961d7e.mp3"
  },
  "lunch": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/bb/a6/bba63abce25e43b4d8d2b074750ebee4.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/bb/a6/bba63abce25e43b4d8d2b074750ebee4.mp3"
  },
  "machine": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/14/75/14754f13e5280c5d49d2ae536c2d57e2.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/14/75/14754f13e5280c5d49d2ae536c2d57e2.mp3"
  },
  "map": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/1d/78/1d78dc8ed51214e518b5114fe24490ae.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/1d/78/1d78dc8ed51214e518b5114fe24490ae.mp3"
  },
  "measure": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/29/25/2925f77709f2db1f915deadc2940db88.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/29/25/2925f77709f2db1f915deadc2940db88.mp3"
  },
  "milk": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/ec/bd/ecbdb882ae865a07d87611437fda0772.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/ec/bd/ecbdb882ae865a07d87611437fda0772.mp3"
  },
  "money": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/97/26/9726255eec083aa56dc0449a21b33190.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/97/26/9726255eec083aa56dc0449a21b33190.mp3"
  },
  "moon": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/6d/4d/6d4db5ff0c117864a02827bad3c361b9.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/6d/4d/6d4db5ff0c117864a02827bad3c361b9.mp3"
  },
  "morning": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/c7/c3/c7c3169c21f1d92e9577871831d067c8.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/c7/c3/c7c3169c21f1d92e9577871831d067c8.mp3"
  },
  "mother": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/6e/e6/6ee6a213cb02554a63b1867143572e70.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/6e/e6/6ee6a213cb02554a63b1867143572e70.mp3"
  },
  "mouth": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/cb/57/cb5786412becb979c90f606f25ad4b4f.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/cb/57/cb5786412becb979c90f606f25ad4b4f.mp3"
  },
  "mum": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/63/cd/63cd0b85fb56ae8cc6496c1d56599ebc.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/63/cd/63cd0b85fb56ae8cc6496c1d56599ebc.mp3"
  },
  "music": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/18/d6/18d6769919266cd0bd6cd78aa405d5d0.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/18/d6/18d6769919266cd0bd6cd78aa405d5d0.mp3"
  },
  "my": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/68/64/6864f389d9876436bc8778ff071d1b6c.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/68/64/6864f389d9876436bc8778ff071d1b6c.mp3"
  },
  "name": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/b0/68/b068931cc450442b63f5b3d276ea4297.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/b0/68/b068931cc450442b63f5b3d276ea4297.mp3"
  },
  "near": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/85/f0/85f06cc816f93b8a6dbb1a494f813358.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/85/f0/85f06cc816f93b8a6dbb1a494f813358.mp3"
  },
  "needs": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/35/ea/35ea8083fa3fa79e8294cb56d079387d.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/35/ea/35ea8083fa3fa79e8294cb56d079387d.mp3"
  },
  "new": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/22/af/22af645d1859cb5ca6da0c484f1f37ea.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/22/af/22af645d1859cb5ca6da0c484f1f37ea.mp3"
  },
  "nine": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/c7/85/c785e1ed2950e3e36b1e2ca01f299a54.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/c7/85/c785e1ed2950e3e36b1e2ca01f299a54.mp3"
  },
  "no": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/7f/a3/7fa3b767c460b54a2be4d49030b349c7.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/7f/a3/7fa3b767c460b54a2be4d49030b349c7.mp3"
  },
  "now": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/97/bc/97bc592b27a9ada2d9a4bb418ed0ebed.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/97/bc/97bc592b27a9ada2d9a4bb418ed0ebed.mp3"
  },
  "nurse": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/07/01/0701aa317da5a004fbf6111545678a6c.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/07/01/0701aa317da5a004fbf6111545678a6c.mp3"
  },
  "one": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/f9/7c/f97c5d29941bfb1b2fdab0874906ab82.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/f9/7c/f97c5d29941bfb1b2fdab0874906ab82.mp3"
  },
  "open": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/7c/ef/7cef8a734855777c2a9d0caf42666e69.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/7c/ef/7cef8a734855777c2a9d0caf42666e69.mp3"
  },
  "orange": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/fe/01/fe01d67a002dfa0f3ac084298142eccd.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/fe/01/fe01d67a002dfa0f3ac084298142eccd.mp3"
  },
  "out": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/c6/82/c68271a63ddbc431c307beb7d2918275.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/c6/82/c68271a63ddbc431c307beb7d2918275.mp3"
  },
  "park": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/fb/45/fb45615cea1183af03479d88ad4da5cd.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/fb/45/fb45615cea1183af03479d88ad4da5cd.mp3"
  },
  "pen": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/03/f0/03f00e8e9d0d0847bb10a3a22334274a.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/03/f0/03f00e8e9d0d0847bb10a3a22334274a.mp3"
  },
  "perhaps": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/48/64/48643de4e709ff78a8f7ce1ba36878b2.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/48/64/48643de4e709ff78a8f7ce1ba36878b2.mp3"
  },
  "phone": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/f7/a4/f7a42fe7211f98ac7a60a285ac3a9e87.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/f7/a4/f7a42fe7211f98ac7a60a285ac3a9e87.mp3"
  },
  "pin": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/8a/6f/8a6f503814aa4a7cd863e68c7778fbdb.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/8a/6f/8a6f503814aa4a7cd863e68c7778fbdb.mp3"
  },
  "poor": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/5c/ff/5cffaf9375c0ef1d49451b062abdac80.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/5c/ff/5cffaf9375c0ef1d49451b062abdac80.mp3"
  },
  "public": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/4c/91/4c9184f37cff01bcdc32dc486ec36961.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/4c/91/4c9184f37cff01bcdc32dc486ec36961.mp3"
  },
  "put": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/8e/13/8e13ffc9fd9d6a6761231a764bdf106b.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/8e/13/8e13ffc9fd9d6a6761231a764bdf106b.mp3"
  },
  "quick": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/1d/f3/1df3746a4728276afdc24f828186f73a.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/1d/f3/1df3746a4728276afdc24f828186f73a.mp3"
  },
  "rain": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/23/67/23678db5efde9ab46bce8c23a6d91b50.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/23/67/23678db5efde9ab46bce8c23a6d91b50.mp3"
  },
  "red": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/bd/a9/bda9643ac6601722a28f238714274da4.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/bd/a9/bda9643ac6601722a28f238714274da4.mp3"
  },
  "right": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/7c/4f/7c4f29407893c334a6cb7a87bf045c0d.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/7c/4f/7c4f29407893c334a6cb7a87bf045c0d.mp3"
  },
  "river": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/a5/b0/a5b03048ebe345c488e0ca30eff6ab0c.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/a5/b0/a5b03048ebe345c488e0ca30eff6ab0c.mp3"
  },
  "road": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/3c/68/3c68cbe461787ba38509df85e731f1a6.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/3c/68/3c68cbe461787ba38509df85e731f1a6.mp3"
  },
  "room": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/fe/f2/fef2576d54dbde017a3a8e4df699ef6d.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/fe/f2/fef2576d54dbde017a3a8e4df699ef6d.mp3"
  },
  "saw": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/a0/7a/a07a8f8eab60eaafe24af1016a02fbf3.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/a0/7a/a07a8f8eab60eaafe24af1016a02fbf3.mp3"
  },
  "school": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/75/16/7516c3b35580b3490248629cff5e498c.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/75/16/7516c3b35580b3490248629cff5e498c.mp3"
  },
  "see": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/1e/8e/1e8e42b87a65326b98ced7d3af717a72.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/1e/8e/1e8e42b87a65326b98ced7d3af717a72.mp3"
  },
  "seven": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/bb/3a/bb3aec0fdcdbc2974890f805c585d432.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/bb/3a/bb3aec0fdcdbc2974890f805c585d432.mp3"
  },
  "she": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/9e/b0/9eb0d040ef57f4a06759cf307b657918.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/9e/b0/9eb0d040ef57f4a06759cf307b657918.mp3"
  },
  "ship": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/2a/3f/2a3f1166b041928019e4e8718d628665.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/2a/3f/2a3f1166b041928019e4e8718d628665.mp3"
  },
  "sing": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/db/85/db853ec3ecf7fe4adc358085ba37c278.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/db/85/db853ec3ecf7fe4adc358085ba37c278.mp3"
  },
  "sister": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/da/ff/daffd55e1b8020c7a60a7b6e36afb775.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/da/ff/daffd55e1b8020c7a60a7b6e36afb775.mp3"
  },
  "sit": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/87/d4/87d4eeb7dec7686410748d174c0e0a11.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/87/d4/87d4eeb7dec7686410748d174c0e0a11.mp3"
  },
  "sits": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/94/06/940686b72f8e8b7a1f03207d8ec92e32.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/94/06/940686b72f8e8b7a1f03207d8ec92e32.mp3"
  },
  "sofa": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/7a/2c/7a2cc8b443e7cf567a8635724b08185a.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/7a/2c/7a2cc8b443e7cf567a8635724b08185a.mp3"
  },
  "start": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/ea/2b/ea2b2676c28c0db26d39331a336c6b92.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/ea/2b/ea2b2676c28c0db26d39331a336c6b92.mp3"
  },
  "station": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/e8/ed/e8ed3f2846110837f3adb8015ccad5ec.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/e8/ed/e8ed3f2846110837f3adb8015ccad5ec.mp3"
  },
  "stop": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/ef/39/ef399b2d446bb37b7c32ad2cc1b6045b.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/ef/39/ef399b2d446bb37b7c32ad2cc1b6045b.mp3"
  },
  "streets": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/b9/6b/b96b32aa879d9a4eba231bfebf46bff1.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/b9/6b/b96b32aa879d9a4eba231bfebf46bff1.mp3"
  },
  "summer": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/6b/16/6b1628b016dff46e6fa35684be6acc96.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/6b/16/6b1628b016dff46e6fa35684be6acc96.mp3"
  },
  "sun": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/eb/d5/ebd556e6dfc99dbed29675ce1c6c68e5.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/eb/d5/ebd556e6dfc99dbed29675ce1c6c68e5.mp3"
  },
  "support": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/43/49/434990c8a25d2be94863561ae98bd682.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/43/49/434990c8a25d2be94863561ae98bd682.mp3"
  },
  "sure": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/d5/e1/d5e1f5a7f2fe3dab21da19f1c04fbd2b.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/d5/e1/d5e1f5a7f2fe3dab21da19f1c04fbd2b.mp3"
  },
  "table": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/aa/b9/aab9e1de16f38176f86d7a92ba337a8d.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/aa/b9/aab9e1de16f38176f86d7a92ba337a8d.mp3"
  },
  "talk": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/64/b5/64b59718a47cf57a5e4f8443ff43d117.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/64/b5/64b59718a47cf57a5e4f8443ff43d117.mp3"
  },
  "tea": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/72/39/7239ea2b5dc943f61f3c0a0276c20974.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/72/39/7239ea2b5dc943f61f3c0a0276c20974.mp3"
  },
  "teacher": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/8d/78/8d788385431273d11e8b43bb78f3aa41.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/8d/78/8d788385431273d11e8b43bb78f3aa41.mp3"
  },
  "television": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/79/46/79464212afb7fd6c38699d0617eaedeb.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/79/46/79464212afb7fd6c38699d0617eaedeb.mp3"
  },
  "ten": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/b1/b9/b1b9a972ccd8c962a473909b97007eb4.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/b1/b9/b1b9a972ccd8c962a473909b97007eb4.mp3"
  },
  "thank": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/f5/ab/f5ab96926a6a561aab7ecb4ba7c915d4.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/f5/ab/f5ab96926a6a561aab7ecb4ba7c915d4.mp3"
  },
  "that": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/21/58/21582c6c30be1217322cdb9aebaf4a59.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/21/58/21582c6c30be1217322cdb9aebaf4a59.mp3"
  },
  "there": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/d8/50/d850f04cdb48312a9be171e214c0b4ee.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/d8/50/d850f04cdb48312a9be171e214c0b4ee.mp3"
  },
  "think": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/54/c8/54c84b40e9ff5a31472904a0cd2f0a17.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/54/c8/54c84b40e9ff5a31472904a0cd2f0a17.mp3"
  },
  "this": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/9e/92/9e925e9341b490bfd3b4c4ca3b0c1ef2.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/9e/92/9e925e9341b490bfd3b4c4ca3b0c1ef2.mp3"
  },
  "three": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/35/d6/35d6d33467aae9a2e3dccb4b6b027878.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/35/d6/35d6d33467aae9a2e3dccb4b6b027878.mp3"
  },
  "time": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/07/cc/07cc694b9b3fc636710fa08b6922c42b.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/07/cc/07cc694b9b3fc636710fa08b6922c42b.mp3"
  },
  "top": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/b2/83/b28354b543375bfa94dabaeda722927f.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/b2/83/b28354b543375bfa94dabaeda722927f.mp3"
  },
  "tour": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/f0/a4/f0a4025b3b49b3e256004503ee31df8c.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/f0/a4/f0a4025b3b49b3e256004503ee31df8c.mp3"
  },
  "tourist": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/9c/07/9c0763361a96027a33f2f28667033686.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/9c/07/9c0763361a96027a33f2f28667033686.mp3"
  },
  "town": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/71/98/7198cda575b51b68a0dc83f5d66c2aee.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/71/98/7198cda575b51b68a0dc83f5d66c2aee.mp3"
  },
  "toy": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/10/01/10016b6ed5a5b09be08133fa2d282636.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/10/01/10016b6ed5a5b09be08133fa2d282636.mp3"
  },
  "train": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/61/b3/61b3a8faa9c1091806675c230a9abe64.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/61/b3/61b3a8faa9c1091806675c230a9abe64.mp3"
  },
  "travel": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/69/26/69266c67e75c946ef9b4144b0554326d.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/69/26/69266c67e75c946ef9b4144b0554326d.mp3"
  },
  "tree": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/c0/af/c0af77cf8294ff93a5cdb2963ca9f038.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/c0/af/c0af77cf8294ff93a5cdb2963ca9f038.mp3"
  },
  "try": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/08/0f/080f651e3fcca17df3a47c2cecfcb880.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/08/0f/080f651e3fcca17df3a47c2cecfcb880.mp3"
  },
  "turn": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/a8/50/a850c17cba5eb16b0d3d40a106333bd5.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/a8/50/a850c17cba5eb16b0d3d40a106333bd5.mp3"
  },
  "usually": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/4a/1d/4a1dbf51be367295c9f70cf609f9b3a0.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/4a/1d/4a1dbf51be367295c9f70cf609f9b3a0.mp3"
  },
  "very": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/f0/16/f016441d00c16c9b912d05e9d81d894d.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/f0/16/f016441d00c16c9b912d05e9d81d894d.mp3"
  },
  "vision": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/f4/20/f42087059b37ae7f4d9f0d3a475801a8.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/f4/20/f42087059b37ae7f4d9f0d3a475801a8.mp3"
  },
  "voice": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/b9/56/b95677216e439d96ec4fba1240a3c1f8.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/b9/56/b95677216e439d96ec4fba1240a3c1f8.mp3"
  },
  "wash": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/15/c7/15c74daa224f69d40cf879d573981d67.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/15/c7/15c74daa224f69d40cf879d573981d67.mp3"
  },
  "watch": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/d2/97/d2974c96dc96b3f30a6168bcc4b25b02.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/d2/97/d2974c96dc96b3f30a6168bcc4b25b02.mp3"
  },
  "water": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/94/60/9460370bb0ca1c98a779b1bcc6861c2c.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/94/60/9460370bb0ca1c98a779b1bcc6861c2c.mp3"
  },
  "we": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/ff/1c/ff1ccf57e98c817df1efcd9fe44a8aeb.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/ff/1c/ff1ccf57e98c817df1efcd9fe44a8aeb.mp3"
  },
  "window": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/05/b8/05b8c74cbd96fbf2de4c1a352702fbf4.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/05/b8/05b8c74cbd96fbf2de4c1a352702fbf4.mp3"
  },
  "work": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/67/e9/67e92c8765a9bc7fb2d335c459de9eb5.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/67/e9/67e92c8765a9bc7fb2d335c459de9eb5.mp3"
  },
  "year": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/84/cd/84cdc76cabf41bd7c961f6ab12f117d8.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/84/cd/84cdc76cabf41bd7c961f6ab12f117d8.mp3"
  },
  "yellow": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/d4/87/d487dd0b55dfcacdd920ccbdaeafa351.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/d4/87/d487dd0b55dfcacdd920ccbdaeafa351.mp3"
  },
  "yes": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/a6/10/a6105c0a611b41b08f1209506350279e.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/a6/10/a6105c0a611b41b08f1209506350279e.mp3"
  },
  "you": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/63/9b/639bae9ac6b3e1a84cebb7b403297b79.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/63/9b/639bae9ac6b3e1a84cebb7b403297b79.mp3"
  },
  "young": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/f6/18/f6182f0359f72aae12fb90d305ccf9eb.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/f6/18/f6182f0359f72aae12fb90d305ccf9eb.mp3"
  },
  "zero": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/d0/2c/d02c4c4cde7ae76252540d116a40f23a.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/d0/2c/d02c4c4cde7ae76252540d116a40f23a.mp3"
  },
  "zoo": {
    "uk": "https://res.iciba.com/resource/amp3/0/0/d2/cb/d2cbe65f53da8607e64173c1a83394fe.mp3",
    "us": "https://res.iciba.com/resource/amp3/1/0/d2/cb/d2cbe65f53da8607e64173c1a83394fe.mp3"
  }
});
